apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sports-scores-job.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sports-scores-job.labels" . | nindent 4 }}
data:
  APP_NAME: {{ required "config.APP_NAME is required" .Values.config.APP_NAME | quote }}
  LOG_LEVEL: {{ required "config.LOG_LEVEL is required" .Values.config.LOG_LEVEL | quote }}
  DATABASE_HOST: {{ required "config.DATABASE_HOST is required" .Values.config.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ required "config.DATABASE_PORT is required" .Values.config.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ required "config.DATABASE_NAME is required" .Values.config.DATABASE_NAME | quote }}
  PGUSER: {{ required "config.PGUSER is required" .Values.config.PGUSER | quote }}