apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sports-scores-job.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sports-scores-job.labels" . | nindent 4 }}
type: Opaque
data:
  PGPASSWORD: {{ required "secrets.PGPASSWORD is required" .Values.secrets.PGPASSWORD | b64enc | quote }}
  WEBHOOK_URL: {{ required "secrets.WEBHOOK_URL is required" .Values.secrets.WEBHOOK_URL | b64enc | quote }}