apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sports-scores-api.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sports-scores-api.labels" . | nindent 4 }}
type: Opaque
data:
  PGPASSWORD: {{ required "secrets.PGPASSWORD is required" .Values.secrets.PGPASSWORD | b64enc | quote }}