apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trmnl-agent.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trmnl-agent.labels" . | nindent 4 }}
data:
  APP_NAME: {{ required "config.APP_NAME is required" .Values.config.APP_NAME | quote }}
  LOG_LEVEL: {{ required "config.LOG_LEVEL is required" .Values.config.LOG_LEVEL | quote }}
  SOURCE_URL: {{ required "config.SOURCE_URL is required" .Values.config.SOURCE_URL | quote }}
  PULL_RETRY: {{ required "config.PULL_RETRY is required" .Values.config.PULL_RETRY | quote }}