apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trmnl-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trmnl-agent.labels" . | nindent 4 }}
type: Opaque
data:
  WEBHOOK_URL: {{ .Values.secrets.webhookUrl | b64enc | quote }}